### PR TITLE
[US13] Create Home page

### PR DESCRIPTION
**Pull request by himik80**

### CODE REVIEW

**Comment by miegami** [comment]
please, merge main into your branch and resolve the conflicts.

**Comment by miegami** [comment]
image
It shouldn't be sticky

**Comment by miegami** [comment]
Please, remove all actions except likes

**Comment by miegami** [comment]
Please, add login and registration buttons

**Comment by miegami** [comment]
Use home page for route /

**Comment by miegami** [comment]
Please, remove custom styles.

**Review by MtTarik — APPROVED** [review]

**Review by MtTarik — APPROVED** [review]

**Review by miegami — APPROVED** [review]

**Pull request merged**
