### PR TITLE
[US2] -  Initialize React application

### PR DESCRIPTION
**Pull request by MtTarik**
US2-requests #3

### CODE REVIEW

**Comment by miegami** [comment]
Please, rename the pull request using the story number and name.

**Comment by miegami** [comment]
Remove .idea folder.

**Comment by miegami** [comment]
Add information on how to run this app from the terminal to the readme.

**Comment by miegami** [comment]
Remove all unnecessary files including images.

**Comment by MtTarik** [comment]
I fixed everything

**Comment by miegami** [comment]
Also, remove reportWebVitals.js, robots.txt, and package-lock.json. And add package-lock.json to the .gitignore.

**Comment by miegami** [comment]
please, resolve merge conflicts and rename the root folder to the social-network-ui

**Review by miegami — APPROVED** [review]

**Review by CoffeeScriptHero — APPROVED** [review]

**Pull request merged**
